baseURL = 'https://HBchevelle68.github.io/'
languageCode = 'en-us'
title = 'HBchevelle68'
theme = 'HB_archie'

# Using Archie syntax highlighter
# pygmentsstyle = "github-dark"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

# Using Hugo syntax highlighter
[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'catppuccin-mocha'
tabWidth = 4


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/HBchevelle68"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2
